import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Flame, ArrowLeft } from 'lucide-react';

export default function TermsAndConditions() {
  const navigate = useNavigate();

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', padding: '24px 16px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 32 }}>
          <div style={{ width: 40, height: 40, borderRadius: 10, background: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', flexShrink: 0 }}>
            <Flame size={20} />
          </div>
          <div>
            <h1 style={{ fontSize: 18, fontWeight: 700, margin: 0 }}>
              Cylinder<span style={{ color: 'var(--primary)' }}>Hub</span>
            </h1>
            <p className="dim" style={{ fontSize: 12, margin: 0 }}>Business Management Platform</p>
          </div>
        </div>

        {/* Card */}
        <div className="card" style={{ padding: '32px 40px' }}>
          <h2 style={{ fontSize: 22, fontWeight: 700, marginTop: 0, marginBottom: 4 }}>Terms and Conditions</h2>
          <p className="dim" style={{ fontSize: 13, marginBottom: 28 }}>Last updated: June 6, 2026</p>

          <Section title="1. Acceptance of Terms">
            <p>By accessing or using the CylinderHub platform ("Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, do not use the Service.</p>
            <p>These terms apply to all users of the platform, including administrators and salesmen.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>CylinderHub is a business management platform designed for LPG cylinder distribution businesses. The Service includes:</p>
            <ul>
              <li>Inventory and stock management for cylinder tracking.</li>
              <li>Sales recording and customer management.</li>
              <li>Salesman allocation and End of Day (EOD) reconciliation.</li>
              <li>Financial reporting, due collection tracking, and profit analytics.</li>
              <li>Purchase management and supplier tracking.</li>
            </ul>
          </Section>

          <Section title="3. User Accounts and Access">
            <ul>
              <li>Accounts are created by administrators. You may not create an account without authorization from your organization's admin.</li>
              <li>You are responsible for maintaining the confidentiality of your login credentials. Do not share your password with others.</li>
              <li>You must immediately notify your administrator if you suspect unauthorized access to your account.</li>
              <li>Administrators are responsible for managing user access, including deactivating accounts of former employees.</li>
            </ul>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree to use the Service only for its intended business purposes. You must not:</p>
            <ul>
              <li>Access another user's data without authorization.</li>
              <li>Enter false, misleading, or fraudulent data into the system.</li>
              <li>Attempt to reverse-engineer, hack, or circumvent any security measures.</li>
              <li>Use the Service for any unlawful purpose or in violation of any regulations.</li>
              <li>Interfere with or disrupt the platform's operation or servers.</li>
              <li>Attempt to access admin features using a salesman account or vice versa.</li>
            </ul>
          </Section>

          <Section title="5. Data Accuracy and Responsibility">
            <ul>
              <li>You are responsible for the accuracy of all data you enter into the platform, including sales records, payment amounts, and reconciliation figures.</li>
              <li>EOD reconciliation submissions are considered final by you. Corrections require administrator authorization.</li>
              <li>CylinderHub is not responsible for business decisions made based on data entered or reports generated by the platform.</li>
            </ul>
          </Section>

          <Section title="6. Intellectual Property">
            <p>All software, code, design, and content comprising the CylinderHub platform is the intellectual property of the platform owner. You are granted a limited, non-exclusive, non-transferable license to use the Service for your organization's internal business operations. You may not copy, modify, distribute, or create derivative works from the platform.</p>
          </Section>

          <Section title="7. Data Ownership">
            <p>Your organization retains ownership of all business data you enter into the platform (sales records, customer data, inventory data, etc.). We hold this data on your behalf and do not claim any ownership over it. Upon account termination, data can be exported or deleted upon request.</p>
          </Section>

          <Section title="8. Service Availability">
            <p>We aim to maintain high availability of the Service but do not guarantee uninterrupted access. Scheduled maintenance, updates, or unforeseen technical issues may cause temporary downtime. We are not liable for any losses arising from service interruptions.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>To the maximum extent permitted by applicable law, CylinderHub and its operators shall not be liable for:</p>
            <ul>
              <li>Any indirect, incidental, or consequential damages arising from use of the Service.</li>
              <li>Loss of business data due to user error or unauthorized access.</li>
              <li>Financial decisions made based on reports or data generated by the platform.</li>
              <li>Service interruptions or downtime.</li>
            </ul>
            <p>Our total liability shall not exceed the amount paid for the Service in the 12 months preceding the claim.</p>
          </Section>

          <Section title="10. Termination">
            <p>We reserve the right to suspend or terminate access to the Service if these Terms are violated. Administrators may deactivate individual user accounts at any time. Upon termination, your right to access the Service ceases immediately.</p>
          </Section>

          <Section title="11. Changes to Terms">
            <p>We may update these Terms from time to time. The updated version will be reflected by the "Last updated" date above. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
          </Section>

          <Section title="12. Governing Law">
            <p>These Terms shall be governed by and construed in accordance with the laws of Bangladesh. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Bangladesh.</p>
          </Section>

          <Section title="13. Contact">
            <p>For questions about these Terms and Conditions, please contact your organization's CylinderHub administrator or reach out through the platform's support channel.</p>
          </Section>
        </div>

        {/* Back link */}
        <button
          onClick={() => navigate('/login')}
          style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: 'none', cursor: 'pointer', color: 'var(--primary)', fontSize: 14, fontWeight: 500, marginTop: 24, padding: 0 }}
        >
          <ArrowLeft size={15} />
          Back to Login
        </button>

      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 10, marginTop: 0, color: 'var(--text)' }}>{title}</h3>
      <div style={{ fontSize: 14, lineHeight: 1.7, color: 'var(--text-2)' }}>{children}</div>
    </div>
  );
}
